version: '3.7'

services:
    app:
      container_name: 'payment-app'
      build: .
      ports:
        - 3333:3333
      volumes:
        - .:/usr/app
      depends_on:
        - db
      links:
        - db
    
    db:
      container_name: 'mysql_database'
      image: mysql:5.7.31
      command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
      restart: always
      ports: 
        - '3308:3306'
      environment: 
        - MYSQL_ROOT_PASSWORD=root
        - TZ=America/Sao_Paulo